version: '3'

networks:
  backend:

volumes:
  minio-data:
    driver: local


services:

  #############################################################################
  ###### Data Bases ###########################################################
  #############################################################################

  postgres-customer:
    container_name: customer-service-db
    image: postgres:14
    environment:
      POSTGRES_DB: customer-service
      POSTGRES_USER: aaiyvan
      POSTGRES_PASSWORD: aaiyvan
    ports:
      - "5433:5432"
    volumes:
      - ./volumes/customer:/data/postgres

  postgres-auth:
    container_name: auth-service-db
    image: postgres:14
    environment:
      POSTGRES_DB: auth-service
      POSTGRES_USER: aaiyvan
      POSTGRES_PASSWORD: aaiyvan
    ports:
      - "5434:5432"
    volumes:
      - ./volumes/auth:/data/postgres

  postgres-storage:
    container_name: storage-service-db
    image: postgres:14
    environment:
      POSTGRES_DB: storage-service
      POSTGRES_USER: aaiyvan
      POSTGRES_PASSWORD: aaiyvan
    ports:
      - "5438:5432"
    volumes:
      - ./volumes/customer:/data/postgres

  postgres-news:
    container_name: news-service-db
    image: postgres:14
    environment:
      POSTGRES_DB: news-service
      POSTGRES_USER: aaiyvan
      POSTGRES_PASSWORD: aaiyvan
    ports:
      - "5437:5432"
    volumes:
      - ./volumes/news:/data/postgres

  postgres-loan:
    container_name: loan-service-db
    image: postgres:14
    environment:
      POSTGRES_DB: loan-service
      POSTGRES_USER: aaiyvan
      POSTGRES_PASSWORD: aaiyvan
    ports:
      - "5436:5432"
    volumes:
      - ./volumes/loan:/data/postgres

  mongo-credit-card:
    container_name: credit-card-service-db
    image: mongo:7
    environment:
      MONGO_INITDB_DATABASE: credit-card-service
      MONGO_INITDB_ROOT_USERNAME: aaiyvan
      MONGO_INITDB_ROOT_PASSWORD: aaiyvan
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/credit-card:/data/mongo-db

  redis:
    image: redis
    ports:
      - "6379:6379"

  #############################################################################
  ###### Services #############################################################
  #############################################################################

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - './config/keycloak/import:/opt/keycloak/data/import'
    ports:
      - "8082:8080"
    command: start-dev --import-realm

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server ~/minio --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - ./volumes/storage:/data/minio