spring:
  main:
    banner-mode: off
  application:
    name: qr-service
qr:
  width: 600
  height: 600
  charset: UTF-8
server:
  port: 8070
logging:
  level:
    org.springframework:
      web: debug
      security: debug