apiVersion: v1
kind: PersistentVolume
metadata:
  name: credit-card-db-pv
  labels:
    app: credit-card-db
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: credit-card-db-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-card-db
  labels:
    app: credit-card-db
spec:
  selector:
    matchLabels:
      app: credit-card-db
  template:
    metadata:
      labels:
        app: credit-card-db
    spec:
      containers:
        - name: credit-card-db
          image: mongo:7
          ports:
            - containerPort: 27017
              name: mongodb
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-persistent-storage
      volumes:
        - name: mongodb-persistent-storage
          persistentVolumeClaim:
            claimName: credit-card-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: credit-card-db-svc
spec:
  ports:
    - port: 27017
  selector:
    app: credit-card-db
  clusterIP: None