image: 192.168.49.1:5000/banking-system/customer-service:24.1.1
vmagent:
  image: victoriametrics/vmagent:v1.93.12
  remoteWrite:
    url: http://banking-system.svc.cluster.local:8428/api/v1/write
ingress:
  host: api.banking.system.192.168.49.2.nip.io