spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/customer-service
    username: aaiyvan
    password: aaiyvan
  jpa:
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8081